### ISSUE TITLE
The plugin throws foreach() warnings

### ISSUE THREAD

**Issue by isaumya** [factmaven/disable-blogging#10]
The plugin is throwing PHP warning. 

1 at `settings-page.php` line 101 for invalid argument inside the `foreach()` and another error like this:

> **PHP Warning**:  Invalid argument supplied for foreach() in `/home/example/public_html/example/wp-admin/includes/plugin.php `on `line 1422`

Please make it stop. It is making my error_log file inside wp-admin huge.

**Comment by houseraevan** [comment]
Hi there, we're looking into this.

**Comment by isaumya** [comment]
Please let me know when this is fixed.

There was two foeareach() error, one at line 101 and the other at line 1422.

**Comment by houseraevan** [comment]
This issue has been fixed and will roll out with the next update soon along with additional features. Thank you.
