### ISSUE TITLE
Gutenberg glitch

### ISSUE THREAD

**Issue by elosha** [factmaven/disable-blogging#20]
Wordpress 5.6 shows a severe glitch in Gutenberg when _disable-blogging_ is active. Please fix soon because this is a real showstopper 😅

Edit: Suddenly the issue is gone on my site … weird!

Plugin disabled:
![disabled](https://user-images.githubusercontent.com/30213185/104457882-83d88480-55a2-11eb-9520-8eb1e6aa670e.png)
Plugin enabled:
![enabled](https://user-images.githubusercontent.com/30213185/104457875-81762a80-55a2-11eb-9622-420e7cb95213.png)

**Comment by joshuadavidnelson** [comment]
Hey @elosha - your edit implies perhaps this isn't an issue anymore? I am unable to replicate, wondering if we can close this issue or if this is still something that needs to be fixed. If you are still experiencing this, can you confirm which them and WordPress version you are running?

**Comment by elosha** [comment]
Yes, seems it was a glitch, I can't reproduce. Theme was custom, currently running current version. Thanks!
