### ISSUE TITLE
Handling of Activity on the Dashboard

### ISSUE THREAD

**Issue by sectsect** [factmaven/disable-blogging#4]
Hi @factmaven,

This is a proposal because it might be different from the purpose of this Plugin.
I'm using this Plugin to remove the default post type `post`.
In many cases, I have multiple `custom post types`.

`Recent Posts` and `Recent Draft` in activity on dashboard should be modified to all `custom post types` other than default post type `post` rather than be removed.

What do you think about it?

**Comment by houseraevan** [comment]
Hi @sectsect,

From what I understand with your proposal is that you want all custom post types to be shown in the **Activity** meta box in the _Dashboard_? If that's not what you mean, may you please elaborate?

![Activity Meta Box](https://i.imgur.com/wwMvvhH.png)

**Comment by sectsect** [comment]
@factmaven 

That's right.
but, If the purpose of this Plugin is "Disable '**All**' Blogging", it might be better to be removed.

Thank you for your consideration of my request.

**Comment by houseraevan** [comment]
@sectsect 

Thanks for your input. The plugin is mainly geared towards disabling all blog related functions, including the meta boxes.

At the moment, I personally don't know of a way to repurpose the "Activity" widget to show your custom post types other than creating a new meta box from scratch. However, if you know of way and share your code, I'd be more than happy to take a look at it and consider it for the next update.

Feel free to give us more suggestions to improve our plugin.

**Comment by sectsect** [comment]
@factmaven 

I see.

I confirmed the purpose of this plugin. And I've submitted a `Pull Request`. https://github.com/factmaven/disable-blogging/pull/5
This is for enabling the Activity on Dashboard & Modify the post-type to all `custom-post-types` in `Recently Published`.

<img width="1182" alt="capture 2016-10-02 at 7 12 51" src="https://cloud.githubusercontent.com/assets/5554826/19019029/d5224910-88b1-11e6-9842-c48a39547683.png">

Many Thanks.
