### ISSUE TITLE
filter for disabling reordering of menu

### ISSUE THREAD

**Issue by Hube2** [factmaven/disable-blogging#7]
Love the plugin, can you add some type of a filter to not reorder the admin menu to put pages at the top? While I want to disable blogging on a site I don't really want the menu order changed, at least on the current site I am working on since things like products are more important than pages.

Thanks,

~JH

**Comment by Hube2** [comment]
And as usual, I find a way to do it after I post the question

```
add_filter('custom_menu_order', '__return_false', 10, 2);
```

**Comment by houseraevan** [comment]
Thanks for the feedback @Hube2. I'll definitely implement this as an option in the next update. This way you don't have to keep adding the custom filter.

**Comment by Hube2** [comment]
Heh, I don't mind filters as long as I can figure out what to add where. What I've done will work on the site I'm working on. but I do have plans on using this plugin on a complicated site where I'm already altering the order the menu so a setting or a filter, either will work I think.

**Comment by houseraevan** [comment]
Added option to disable reorder filter. This will be pushed out to the latest update soon.
