### ISSUE TITLE
i18n: Japanese translation

### ISSUE THREAD

**Issue by houseraevan** [factmaven/disable-blogging#8]
Hi @sectsect,

I merged the changes from #6. When you last said:

> Can you make a other branch from @senlin 's pull request?

Should I make a separate branch for translation? Please confirm.

**Comment by sectsect** [comment]
@factmaven 

Thank you for your support.

You don't need to make a new branch.
I'm gonna submit a pull request to the `master` branch.

**Comment by houseraevan** [comment]
@sectsect 

Great, thanks.

**Comment by houseraevan** [comment]
Merged changes from #9
